In [23]:
from utils import utilities
from pathlib import Path
import numpy as np

In [3]:
DATA_DIR=Path("/media/Extra_Drive/packed_features")

In [5]:
x, y, video_id_list = utilities.load_data(DATA_DIR/'bal_train.h5')

In [29]:
video_id_list[0]

b'--cB2ZVjpnA'


In [11]:
x.shape

(22160, 10, 128)

In [21]:
x[0][0]

array([ 95, 122, 147,  14, 101,  48, 157, 125, 250, 245, 106, 169,  51,
       126,  77, 145, 133,  37, 181, 159,  32, 251, 215, 136, 160, 247,
       154,  43,  95,  27, 136,  96, 113,  61,  72, 255,  74,  91, 167,
       106,   3, 152, 112, 255, 249,  97, 220, 255,  48, 255, 127, 255,
        42,  24, 137, 169, 150, 224,   0,  67, 248, 166,  58,  84,   0,
       143,  55, 100, 171, 255, 124,  69, 127,   6,   0,   0,  43,   0,
       255, 135,  69,  79, 211, 177, 209, 186, 226,  77, 107, 149,  27,
       255,  30, 255,   0,  28, 135, 255, 252, 111,  95, 255, 155,  92,
        67, 227,  78,  97,   0, 255,   0,   0, 219, 113, 255, 154, 109,
       127, 185,   0, 186,   0,  63, 255, 255,   2, 190,   0], dtype=uint8)

In [13]:
y.shape

(22160, 527)

In [14]:
y

array([[False, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [ True, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [15]:
xt, yt = utilities.transform_data(x, y)

In [16]:
xt.shape

(22160, 10, 128)

In [17]:
xt

array([[[-0.2578125, -0.046875 ,  0.1484375, ..., -0.984375 ,
          0.484375 , -1.       ],
        [-0.0390625, -0.1484375,  0.0703125, ..., -0.0390625,
          0.09375  ,  0.9375   ],
        [-0.59375  ,  0.0546875,  0.1875   , ..., -1.       ,
          0.9921875, -1.       ],
        ...,
        [-0.1328125, -0.0546875, -0.1640625, ..., -1.       ,
          0.9921875,  0.9921875],
        [-0.40625  , -0.2421875,  0.3125   , ..., -0.6796875,
          0.9921875,  0.9921875],
        [-0.484375 ,  0.125    , -0.171875 , ..., -0.2421875,
          0.65625  , -1.       ]],

       [[-0.375    ,  0.4140625,  0.6875   , ...,  0.6171875,
         -0.0390625,  0.8203125],
        [-0.578125 ,  0.9921875,  0.3671875, ...,  0.9921875,
          0.6015625, -0.5703125],
        [-0.03125  ,  0.203125 ,  0.2890625, ..., -0.46875  ,
          0.2890625, -1.       ],
        ...,
        [-0.34375  ,  0.21875  ,  0.15625  , ..., -1.       ,
         -0.484375 ,  0.3359375],
        [-0.

In [25]:
xt[0][0][0]*128 + 128

95.0

In [19]:
yt.shape

(22160, 527)

In [20]:
yt

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)