In [1]:
from utils import utilities
from pathlib import Path
import numpy as np

In [2]:
DATA_DIR=Path("/media/Extra_Drive/packed_features")

In [3]:
x, y, video_id_list = utilities.load_data(DATA_DIR/'TEST1.h5')

In [29]:
video_id_list[0]

b'--cB2ZVjpnA'


In [4]:
x.shape

(65, 20, 128)

In [5]:
x[0][0]

array([150,   2, 164,  70, 219,  87,  73, 110, 182, 171,  84,  98, 167,
       170,   6,  84, 164,  86, 131, 212,  20, 230,  59,  75, 108, 165,
       144,  86, 174, 138, 174, 116, 115,  65,  84, 166,  65, 140, 148,
        35,  53, 255,   0,   0,  89,  43,  31, 104,  84, 195, 127,   4,
        76, 136, 151,  81, 118,  62,  54, 208, 163, 117,  38, 178, 116,
       102,  48,  54, 133, 162, 129, 255, 255, 255, 166, 117,   5, 145,
       126, 255,   0, 119, 236, 224,  60,  27, 213, 239, 111, 171, 153,
       255, 230, 255, 202, 162,  62,   0, 255, 255, 230,  35,  44, 154,
       202, 126, 174, 153, 128, 110, 255, 255, 255, 102, 214, 104, 255,
       217,   0, 188, 198,  85, 171,  58, 173,   0,   0, 255], dtype=uint8)

In [13]:
y.shape

(22160, 527)

In [10]:
y

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [6]:
xt, yt = utilities.transform_data(x, y)

In [7]:
xt.shape

(65, 20, 128)

In [8]:
xt

array([[[ 0.171875 , -0.984375 ,  0.28125  , ..., -1.       ,
         -1.       ,  0.9921875],
        [ 0.1796875, -0.953125 ,  0.25     , ..., -1.       ,
         -1.       ,  0.9921875],
        [ 0.171875 , -0.9609375,  0.296875 , ..., -1.       ,
         -1.       ,  0.9921875],
        ...,
        [ 0.1796875, -1.       ,  0.34375  , ..., -1.       ,
         -1.       ,  0.9921875],
        [ 0.1640625, -0.9921875,  0.34375  , ..., -1.       ,
         -1.       ,  0.9921875],
        [ 0.1796875, -0.9609375,  0.3359375, ..., -1.       ,
         -1.       ,  0.9921875]],

       [[ 0.1875   , -0.96875  ,  0.234375 , ..., -1.       ,
         -1.       ,  0.9921875],
        [ 0.2265625, -0.890625 ,  0.28125  , ...,  0.90625  ,
         -1.       ,  0.9921875],
        [ 0.203125 , -0.9140625,  0.3203125, ...,  0.5078125,
         -0.5390625,  0.9921875],
        ...,
        [ 0.1875   , -1.       ,  0.3203125, ..., -1.       ,
         -1.       ,  0.9921875],
        [ 0.

In [9]:
xt[0][0][0]*128 + 128

150.0

In [19]:
yt.shape

(22160, 527)

In [11]:
yt

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)